In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 데이터 읽기df_A = pd.read_csv('Bidding_csv/Bidding_A.csv', encoding='cp949')  # 제품명과 제품코드
df_B = pd.read_csv('Bidding_csv/Bidding_B.csv', encoding='cp949')
df_H = pd.read_csv('Bidding_csv/Bidding_H.csv', encoding='cp949')
df_I = pd.read_csv('Bidding_csv/Bidding_I.csv', encoding='cp949')
df_L = pd.read_csv('Bidding_csv/Bidding_L.csv', encoding='cp949')  # Price만 있음
df_cost = pd.read_csv('Bidding_csv/Bidding_OriginalPrice.csv', encoding='cp949')  # 원가
df_target = pd.read_csv('Bidding_csv/Bidding_target.csv', encoding='cp949')  # 영업회신
df_tier = pd.read_csv('Bidding_csv/Bidding_Tier.csv', encoding='cp949')  # Tier

In [25]:
df_target

         T         할당비율  할당업체수 Target TargetVolume  Unnamed: 5
0  Model A  40/30/20/10      4      Y   2,600,000          NaN
1  Model B  40/30/20/10      4      Y   5,500,000          NaN
2  Model C        70/30      2      Y     200,000          NaN
3  Model D        60/40      2      Y     500,000          NaN
4  Model E  40/30/20/10      4      N            -         NaN
5  Model F        60/40      2      Y     700,000          NaN
6  Model G  40/30/20/10      4      N            -         NaN
7  Model H        70/30      2      Y     350,000          NaN
8  Model I  40/30/20/10      4      Y   8,000,000          NaN
9  Model J  40/30/20/10      4      N   6,500,000          NaN

In [26]:
df_target.drop(columns=['Unnamed: 5'], inplace=True)

In [28]:
df_tier

   업체      구분          수량
0   A   DVT_1     50,000
1   A   DVT_2    100,000
2   A   DVT_3    200,000
3   A   DVT_4    300,000
4   A   DVT_5    400,000
.. ..     ...         ...
68  L   DVT_8  3,000,000
69  L   DVT_9  3,500,000
70  L  DVT_10  4,000,000
71  L  DVT_11  4,500,000
72  L  DVT_12  5,000,000

[73 rows x 3 columns]

In [32]:
df_target

         T         할당비율  할당업체수 Target TargetVolume
0  Model A  40/30/20/10      4      Y   2,600,000
1  Model B  40/30/20/10      4      Y   5,500,000
2  Model C        70/30      2      Y     200,000
3  Model D        60/40      2      Y     500,000
4  Model E  40/30/20/10      4      N            -
5  Model F        60/40      2      Y     700,000
6  Model G  40/30/20/10      4      N            -
7  Model H        70/30      2      Y     350,000
8  Model I  40/30/20/10      4      Y   8,000,000
9  Model J  40/30/20/10      4      N   6,500,000

In [ ]:
for idx, row in df_B.iterrows():
    nan_cols = row[row.isnull()].index.tolist()
    if nan_cols:
        print(f"{row['Model']}: NaN {len(nan_cols)}개 ({nan_cols[0]} ~ {nan_cols[-1]})")
    else: 
        print(f"{row['Model']}: 빈 값 없네요")
print(df_B.isnull().sum(axis=1))

Model A: 빈 값 없네요
Model B: 빈 값 없네요
Model C: NaN 21개 (DVT_5 ~ DVT_25)
Model D: NaN 20개 (DVT_6 ~ DVT_25)
Model E: 빈 값 없네요
Model F: NaN 16개 (DVT_10 ~ DVT_25)
Model G: 빈 값 없네요
Model H: NaN 19개 (DVT_7 ~ DVT_25)
Model I: 빈 값 없네요
Model J: 빈 값 없네요
0     0
1     0
2    21
3    20
4     0
5    16
6     0
7    19
8     0
9     0
dtype: int64

In [55]:
for idx, row in df_B.iterrows():
    nan_cols = row[row.isnull()].index.tolist()
    if nan_cols:
        print(f"{row['Model']}: NaN {len(nan_cols)}개 ({nan_cols[0]} ~ {nan_cols[-1]})")
    else: 
        print(f"{row['Model']}: 빈 값 없네요")
print(df_B.isnull().sum(axis=1))

Model A: 빈 값 없네요
Model B: 빈 값 없네요
Model C: NaN 21개 (DVT_5 ~ DVT_25)
Model D: NaN 20개 (DVT_6 ~ DVT_25)
Model E: 빈 값 없네요
Model F: NaN 16개 (DVT_10 ~ DVT_25)
Model G: 빈 값 없네요
Model H: NaN 19개 (DVT_7 ~ DVT_25)
Model I: 빈 값 없네요
Model J: 빈 값 없네요
0     0
1     0
2    21
3    20
4     0
5    16
6     0
7    19
8     0
9     0
dtype: int64

In [63]:
for idx, row in df_H.iterrows():
    nan_cols = row[row.isnull()].index.tolist()
    if nan_cols:
        print(f"{row['Model']}: NaN {len(nan_cols)}개 ({nan_cols[0]} ~ {nan_cols[-1]})")
    else: 
        print(f"{row['Model']}: 빈 값 없네요")
print(df_H.isnull().sum(axis=1))

Model A: 빈 값 없네요
Model B: 빈 값 없네요
Model C: 빈 값 없네요
Model D: 빈 값 없네요
Model E: 빈 값 없네요
Model F: 빈 값 없네요
Model G: 빈 값 없네요
Model H: 빈 값 없네요
Model I: 빈 값 없네요
Model J: 빈 값 없네요
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [68]:
for idx, row in df_I.iterrows():
    nan_cols = row[row.isnull()].index.tolist()
    if nan_cols:
        print(f"{row['Model']}: NaN {len(nan_cols)}개 ({nan_cols[0]} ~ {nan_cols[-1]})")
    else: 
        print(f"{row['Model']}: 빈 값 없네요")
print(df_I.isnull().sum(axis=1))
print(f"Total columns: {len(df_I.columns)}")

Model A: 빈 값 없네요
Model B: 빈 값 없네요
Model C: 빈 값 없네요
Model D: 빈 값 없네요
Model E: 빈 값 없네요
Model F: 빈 값 없네요
Model G: 빈 값 없네요
Model H: 빈 값 없네요
Model I: 빈 값 없네요
Model J: 빈 값 없네요
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64
Total columns: 13

In [66]:
df_L

,Model,Demand,Price,Capa,DVT_0,DVT_1,DVT_2,DVT_3,DVT_4,DVT_5,DVT_6,DVT_7,DVT_8,DVT_9,DVT_10,DVT_11,DVT_12
0,Model A,"6,521,238",42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Model B,"13,784,526",28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Model C,"326,540",105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Model D,"894,456",63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Model E,"8,955,420",35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Model F,"1,235,468",66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Model G,"5,648,412",50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Model H,"556,984",88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Model I,"20,365,480",19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Model J,"16,846,513",25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df_cost

     Model  원가
0  Model A  35
1  Model B  22
2  Model C  80
3  Model D  53
4  Model E  28
5  Model F  60
6  Model G  37
7  Model H  82
8  Model I  13
9  Model J  16

In [75]:
df_target

         T         할당비율  할당업체수 Target TargetVolume
0  Model A  40/30/20/10      4      Y   2,600,000
1  Model B  40/30/20/10      4      Y   5,500,000
2  Model C        70/30      2      Y     200,000
3  Model D        60/40      2      Y     500,000
4  Model E  40/30/20/10      4      N            -
5  Model F        60/40      2      Y     700,000
6  Model G  40/30/20/10      4      N            -
7  Model H        70/30      2      Y     350,000
8  Model I  40/30/20/10      4      Y   8,000,000
9  Model J  40/30/20/10      4      N   6,500,000

In [81]:
df_tier

   업체      구분          수량
0   A   DVT_1     50,000
1   A   DVT_2    100,000
2   A   DVT_3    200,000
3   A   DVT_4    300,000
4   A   DVT_5    400,000
.. ..     ...         ...
68  L   DVT_8  3,000,000
69  L   DVT_9  3,500,000
70  L  DVT_10  4,000,000
71  L  DVT_11  4,500,000
72  L  DVT_12  5,000,000

[73 rows x 3 columns]

In [34]:
for name, df in [('A', df_A), ('B', df_B), ('H', df_H), ('I', df_I), ('L', df_L), 
                  ('cost', df_cost), ('target', df_target), ('tier', df_tier)]:
    print(f"\n=== {name} ===")
    print(f"행: {len(df)}, 열: {len(df.columns)}")
    print(f"컬럼: {list(df.columns)}")

=== A ===
행: 9, 열: 23
컬럼: ['Model', 'Demand', 'Price', 'Capa', 'DVT_0', 'DVT_1', 'DVT_2', 'DVT_3', 'DVT_4', 'DVT_5', 'DVT_6', 'DVT_7', 'DVT_8', 'DVT_9', 'DVT_10', 'DVT_11', 'DVT_12', 'DVT_13', 'DVT_14', 'DVT_15', 'DVT_16', 'DVT_17', 'DVT_18']

=== B ===
행: 10, 열: 30
컬럼: ['Model', 'Demand', 'Price', 'Capa', 'DVT_0', 'DVT_1', 'DVT_2', 'DVT_3', 'DVT_4', 'DVT_5', 'DVT_6', 'DVT_7', 'DVT_8', 'DVT_9', 'DVT_10', 'DVT_11', 'DVT_12', 'DVT_13', 'DVT_14', 'DVT_15', 'DVT_16', 'DVT_17', 'DVT_18', 'DVT_19', 'DVT_20', 'DVT_21', 'DVT_22', 'DVT_23', 'DVT_24', 'DVT_25']

=== H ===
행: 10, 열: 16
컬럼: ['Model', 'Demand', 'Price', 'Capa', 'DVT_0', 'DVT_1', 'DVT_2', 'DVT_3', 'DVT_4', 'DVT_5', 'DVT_6', 'DVT_7', 'DVT_8', 'DVT_9', 'DVT_10', 'Unnamed: 15']

=== I ===
행: 10, 열: 13
컬럼: ['Model', 'Demand', 'Price', 'Capa', 'DVT_0', 'DVT_1', 'DVT_2', 'DVT_3', 'DVT_4', 'DVT_5', 'DVT_6', 'DVT_7', 'DVT_8']

=== L ===
행: 10, 열: 17
컬럼: ['Model', 'Demand', 'Price', 'Capa', 'DVT_0', 'DVT_1', 'DVT_2', 'DVT_3', 'DVT_4', 'DVT_5', 'DVT_6', 'DVT_7', 'DVT_8', 'DVT_9', 'DVT_10', 'DVT_11', 'DVT_12']

=== cost ===
행: 10, 열: 2
컬럼: ['Model', '원가']

=== target ===
행: 10, 열: 5
컬럼: ['T', '할당비율', '할당업체수', 'Target', 'TargetVolume']

=== tier ===
행: 73, 열: 3
컬럼: ['업체', '구분', '수량']